version: "3.8"
services:
    database:
        image: postgres:13.5
        restart: always
        environment:
            - POSTGRES_USER=app
            - POSTGRES_PASSWORD=d!@O9p7.4Fg2a
        volumes:
            - database:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DATABASE_URL=${DATABASE_URL}
        depends_on:
            - database
        ports:
            - "3000:3000"

volumes:
    database:
